var T=Object.defineProperty,b=(s,e,t)=>e in s?T(s,e,{enumerable:!0,configurable:!0,writable:!0,value:t}):s[e]=t,c=(s,e,t)=>(b(s,typeof e!="symbol"?e+"":e,t),t);function E(s){const e=[`.${s} img`,`.${s} :not(img)[style*="background-image"]`],t=/background(-image)?:[ a-zA-Z0-9_-]*url\(/;return Array.prototype.forEach.call(document.styleSheets,n=>{try{return Array.prototype.forEach.call(n.rules,i=>{t.test(i.cssText)&&i.selectorText!=="undefined"&&e.push(`.${s} ${i.selectorText}`)})}catch{return!1}}),e.join(", ")}const d="dark-mode-2c9ef1a",o=`theme__root--${d}`,m=`
.${o} {
  filter: invert(0.95) contrast(0.95) saturate(0.5) hue-rotate(180deg)
}
`,g=`
${E(o)} {
  filter: invert(0.95) contrast(0.95) saturate(1.5) hue-rotate(180deg)
}
`;function w(s){return`
  @media (prefers-color-scheme: dark) {
    ${s}
  }
  `}class S{constructor({enableType:e,timeRange:t,rootElement:n}){c(this,"timeRange",{begin:1800,end:2400+700}),c(this,"timeRangeTimerId",0),c(this,"enableType","system"),c(this,"rootElement"),c(this,"styleElement"),this.rootElement=n||document.documentElement,this.enableType=e||this.enableType,this.setEnableType(this.enableType,t)}onSettingUpdate(e,t=3){e||(e=this.rootElement);let n="";t===3?n=m+g:t===2?n=g:t===1&&(n=m);let i=e==null?void 0:e.querySelector("head");if(i||(i=e),this.styleElement||(this.styleElement=document.createElement("style"),i.appendChild(this.styleElement)),this.timeRangeTimerId&&clearTimeout(this.timeRangeTimerId),this.enableType==="always")this.styleElement.innerHTML=n,e==null||e.classList.add(o);else if(this.enableType==="system")this.styleElement.innerHTML=w(n),e==null||e.classList.add(o);else if(this.enableType==="time-range"){const r=()=>{this.isTimeInRange(new Date)?(this.styleElement.innerHTML=n,e==null||e.classList.add(o)):e==null||e.classList.remove(o),this.timeRangeTimerId=setTimeout(r,1e4)};r()}}isDarkMode(){var e;return(e=this.rootElement)==null?void 0:e.classList.contains(o)}isTimeInRange(e){if(this.enableType!=="time-range")return!1;const t=e.getHours(),n=e.getMinutes(),i=t*100+n|0,{begin:r,end:a}=this.timeRange;return r<i&&i<a||r<i+2400&&i+2400<a}setEnableType(e,t){!e||(this.enableType=e,e==="time-range"?this.setEnableTimeRange(t):this.onSettingUpdate())}setEnableTimeRange(e){if(!e)return;const{begin:t,end:n}=e;this.timeRange.begin=t,this.timeRange.end=n<t?n+2400:n,this.onSettingUpdate()}}class v extends S{constructor(e){super(e),this.onMessageFromTopWindow()}onMessageFromTopWindow(){const e={this:this,window},t=(i,r)=>{let a=i;for(let l=0;a&&l<r.length;l++)a=a[r[l]];return a},n=i=>{const r=i.split("."),a=r[0];return e[a]?t(e[a],r.slice(1)):()=>{}};window.addEventListener("message",i=>{try{const{from:r,type:a,data:l}=JSON.parse(i.data);if(r===d&&a==="exec-fn"){const y=l.args.map(f=>n(f));n(l.fn).call(this,...y)}}catch(r){console.log(r)}},!1)}onSettingUpdate(){super.onSettingUpdate(),Array.prototype.forEach.call(window.frames,e=>{try{super.onSettingUpdate(e.document.documentElement,2)}catch{e.postMessage(JSON.stringify({from:d,type:"exec-fn",data:{fn:"this.onSettingUpdate",args:["window.document",2]}}))}})}}function h(s){return window.localStorage.getItem(`dark-mode-2c9ef1a:${s}`)}function u(s,e){window.localStorage.setItem(`dark-mode-2c9ef1a:${s}`,e)}function p(s=h("enableType")||"never",e={begin:0,end:0}){try{const{begin:t,end:n}=JSON.parse(h("timeRange")||"{}");!e.begin&&t&&(e.begin=t),!e.end&&n&&(e.end=n>2400?n-2400:n),u("enableType",s),u("timeRange",JSON.stringify(e))}catch(t){console.log(t)}new v({rootElement:document.documentElement,enableType:s,timeRange:e})}p();chrome.runtime.onMessage.addListener(s=>{const e=JSON.parse(s);p(e.enableType,e.timeRange),window.location.reload()});
